name: Publish to NPM
on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for proper version bumping

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '21'
          registry-url: 'https://registry.npmjs.org'

      - name: Ensure Clean Working Directory
        run: git reset --hard

      - name: Check Git Status Before Bump
        run: git status

      - name: Display Current Package Version
        run: grep '"version"' package.json

      - name: Automated Version Bump
        uses: phips28/gh-action-bump-version@v11.0.7
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          commit-message: 'CI: bumps version to {{version}} [skip ci]'
          tag-prefix: 'v'

      - name: Check Git Status After Bump
        run: git status

      - name: Display Updated Package Version
        run: grep '"version"' package.json

      - name: Install dependencies
        run: npm ci

      - name: Publish package
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}